-- MySQL Script generated by MySQL Workbench
-- 04/03/16 13:24:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`author` ;

CREATE TABLE IF NOT EXISTS `mydb`.`author` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`author_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plugin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`plugin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`plugin` (
  `plugin_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(600) NOT NULL,
  `date` DATE NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`plugin_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_plugin_author_idx` (`author_id` ASC),
  CONSTRAINT `fk_plugin_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`author` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`function`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`function` ;

CREATE TABLE IF NOT EXISTS `mydb`.`function` (
  `function_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(400) NOT NULL,
  `plugin_id` INT NOT NULL,
  PRIMARY KEY (`function_id`),
  INDEX `fk_function_plugin1_idx` (`plugin_id` ASC),
  CONSTRAINT `fk_function_plugin1`
    FOREIGN KEY (`plugin_id`)
    REFERENCES `mydb`.`plugin` (`plugin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`example_call`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`example_call` ;

CREATE TABLE IF NOT EXISTS `mydb`.`example_call` (
  `example_call_id` INT NOT NULL AUTO_INCREMENT,
  `call` VARCHAR(100) NOT NULL,
  `description` VARCHAR(400) NULL,
  `function_id` INT NOT NULL,
  PRIMARY KEY (`example_call_id`),
  UNIQUE INDEX `call_UNIQUE` (`call` ASC),
  INDEX `fk_example_call_function1_idx` (`function_id` ASC),
  CONSTRAINT `fk_example_call_function1`
    FOREIGN KEY (`function_id`)
    REFERENCES `mydb`.`function` (`function_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`option` ;

CREATE TABLE IF NOT EXISTS `mydb`.`option` (
  `option_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`option_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`parameter` ;

CREATE TABLE IF NOT EXISTS `mydb`.`parameter` (
  `parameter_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `function_id` INT NOT NULL,
  `option_id` INT NOT NULL,
  PRIMARY KEY (`parameter_id`),
  INDEX `fk_parameter_function1_idx` (`function_id` ASC),
  INDEX `fk_parameter_option1_idx` (`option_id` ASC),
  CONSTRAINT `fk_parameter_function1`
    FOREIGN KEY (`function_id`)
    REFERENCES `mydb`.`function` (`function_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parameter_option1`
    FOREIGN KEY (`option_id`)
    REFERENCES `mydb`.`option` (`option_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`keyword` ;

CREATE TABLE IF NOT EXISTS `mydb`.`keyword` (
  `keyword_id` INT NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`keyword_id`),
  UNIQUE INDEX `keyword_UNIQUE` (`keyword` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`function_has_keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`function_has_keyword` ;

CREATE TABLE IF NOT EXISTS `mydb`.`function_has_keyword` (
  `function_id` INT NOT NULL,
  `keyword_id` INT NOT NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`function_id`, `keyword_id`),
  INDEX `fk_function_has_keyword_keyword1_idx` (`keyword_id` ASC),
  INDEX `fk_function_has_keyword_function1_idx` (`function_id` ASC),
  CONSTRAINT `fk_function_has_keyword_function1`
    FOREIGN KEY (`function_id`)
    REFERENCES `mydb`.`function` (`function_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_function_has_keyword_keyword1`
    FOREIGN KEY (`keyword_id`)
    REFERENCES `mydb`.`keyword` (`keyword_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parameter_has_keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`parameter_has_keyword` ;

CREATE TABLE IF NOT EXISTS `mydb`.`parameter_has_keyword` (
  `parameter_id` INT NOT NULL,
  `keyword_id` INT NOT NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`parameter_id`, `keyword_id`),
  INDEX `fk_parameter_has_keyword_keyword1_idx` (`keyword_id` ASC),
  INDEX `fk_parameter_has_keyword_parameter1_idx` (`parameter_id` ASC),
  CONSTRAINT `fk_parameter_has_keyword_parameter1`
    FOREIGN KEY (`parameter_id`)
    REFERENCES `mydb`.`parameter` (`parameter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parameter_has_keyword_keyword1`
    FOREIGN KEY (`keyword_id`)
    REFERENCES `mydb`.`keyword` (`keyword_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
